const data = [
  {
    id: 1,
    title: 'apple',
    category: 'men',
    price: 105,
    img: ['/apple-1.jpeg', 'apple-2.jpeg'],
    stockNum: 8,
  },
  {
    id: 2,
    title: 'time',
    category: 'women',
    price: 105,
    img: ['/time-1.jpeg', 'time-2.jpeg'],
    stockNum: 12,
  },
  {
    id: 3,
    title: 'grandpa',
    category: 'women',
    price: 105,
    img: ['/grandpa-1.jpeg', 'grandpa-2.jpeg'],
    stockNum: 10,
  },
  {
    id: 4,
    title: 'tekbant',
    category: 'men',
    price: 105,
    img: ['/tekbant-1.jpeg', 'tekbant-2.jpeg'],
    stockNum: 9,
  },
  {
    id: 5,
    title: 'tarwe',
    category: 'women',
    price: 105,
    img: ['/tarwe-1.jpeg', 'tarwe-2.jpeg'],
    stockNum: 7,
  },
  {
    id: 6,
    title: 'jail',
    category: 'women',
    price: 105,
    img: ['/jail-1.jpeg', 'jail-2.jpeg'],
    stockNum: 5,
  },
  {
    id: 7,
    title: 'mano-duo',
    category: 'men',
    price: 105,
    img: ['/mano-duo-1.jpeg', 'mano-duo-2.jpeg'],
    stockNum: 14,
  },
  {
    id: 8,
    title: 'moontu',
    category: 'men',
    price: 105,
    img: ['/moontu-1.jpeg', 'moontu-2.jpeg'],
    stockNum: 6,
  },
  {
    id: 9,
    title: 'target',
    category: 'women',
    price: 105,
    img: ['/target-1.jpeg', 'target-2.jpeg'],
    stockNum: 9,
  },
  {
    id: 10,
    title: 'nordhug-ocean',
    category: 'bags',
    price: 285,
    img: ['/nordhug-ocean-1.jpeg', 'nordhug-ocean-2.jpeg'],
    stockNum: 4,
  },
  {
    id: 11,
    title: 'nevend-brick',
    category: 'bags',
    price: 255,
    img: ['/nevend-brick-1.jpeg', 'nevend-brick-2.jpeg'],
    stockNum: 8,
  },
  {
    id: 12,
    title: 'nevend-ocean',
    category: 'bags',
    price: 255,
    img: ['/nevend-ocean-1.jpeg', 'nevend-ocean-2.jpeg'],
    stockNum: 8,
  },
  {
    id: 13,
    title: 'nordhug-brick',
    category: 'bags',
    price: 285,
    img: ['/nordhug-brick-1.jpeg', 'nordhug-brick-2.jpeg'],
    stockNum: 11,
  },
  {
    id: 14,
    title: 'nordhug-mini-sulphur',
    category: 'bags',
    price: 305,
    img: ['/nordhug-mini-sulphur-1.jpeg', 'nordhug-mini-sulphur-2.jpeg'],
    stockNum: 6,
  },
  {
    id: 15,
    title: 'ribut',
    category: 'men',
    price: 120,
    img: ['/ribut-1.jpeg', 'ribut-2.jpeg'],
    stockNum: 10,
  },
]

export default data
