export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const HANDLE_INCREMENT = 'HANDLE_INCREMENT'
export const HANDLE_DECREMENT = 'HANDLE_DECREMENT'

export const SELECT_SHIPPING_COMPANY = 'SELECT_SHIPPING_COMPANY'
